DROP TABLE IF EXISTS KUNDE;

CREATE TABLE KUNDE (
    ID INT AUTO_INCREMENT  PRIMARY KEY,
    KUNDEN_NR INT NOT NULL,
    ANREDE VARCHAR(10) NOT NULL,
    NACHNAME VARCHAR(50) NOT NULL,
    VORNAME VARCHAR(50) NOT NULL,
    EMAIL_ADRESSE VARCHAR(50) NOT NULL,
    GEBURTSTAG INT(8),
    GEBURTSMONAT INT(8),
    GEBURTSDATUM INT(8),
    TELEFONNUMMER INT NOT NULL,
    KONTOSTAND INT NOT NULL
);